swagger: '2.0'
info:
  title: Transaction API
  description: API to manage transactions (CRUD operations)
  version: '1.0.0'
host: localhost:3001
basePath: /api/v1
schemes:
  - http

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

paths:
  /transactions:
    get:
      tags:
        - Transaction Module
      summary: Get all transactions
      description: Fetch all transactions for the authenticated user
      security:
        - Bearer: []
      responses:
        '200':
          description: List of transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized (Invalid or missing token)
        '500':
          description: Internal Server Error

  /transactions/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Get a transaction by ID
      description: Retrieve a specific transaction by its ID
      security:
        - Bearer: []
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: The ID of the transaction to retrieve
      responses:
        '200':
          description: Transaction details
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized (Invalid or missing token)
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

    put:
      tags:
        - Transaction Module
      summary: Update or modify a transaction
      description: Modify a transaction by its ID
      security:
        - Bearer: []
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: The ID of the transaction to update
        - in: body
          name: body
          description: Updated transaction payload
          required: true
          schema:
            $ref: '#/definitions/Transactions_2'
      responses:
        '200':
          description: Transaction updated successfully
        '400':
          description: Invalid fields
        '401':
          description: Unauthorized (Invalid or missing token)
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: The unique identifier of the transaction
      amount:
        type: number
        description: Amount involved in the transaction
      type:
        type: string
        description: Type of transaction (e.g., credit, debit)
      date:
        type: string
        format: date-time
        description: The date and time of the transaction
      description:
        type: string
        description: Description or note for the transaction
      category:
        type: string
        description: The category of the transaction (e.g., groceries, salary)
        
  Transactions_2:
    type: object
    properties:
      description:
        type: string
        description: "Optional: Update the description or note for the transaction"
      category:
        type: string
        description: "Optional: Update the category of the transaction (e.g., groceries, salary)"
